#file: noinspection undefined
spring:
  application:
    name: delivery
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5434/commerce"
    username: "caramba"
    password: "yohoho"