#file: noinspection undefined
spring:
  application:
    name: aggregator
kafka:
  bootstrap-server: localhost:9092
  group-id: aggregator
  topics:
    in: telemetry.sensors.v1
    out: telemetry.snapshots.v1
  consumer:
    attempt-timeout: 1000