#file: noinspection undefined
spring:
  application:
    name: analyzer
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5433/telemetry"
    username: "caramba"
    password: "yohoho"
kafka:
  bootstrap-servers: "localhost:9092"
  group-id:
    snapshot: "analyzer.snapshots"
    hub: "analyzer.hubs"
  topics:
    snapshot: "telemetry.snapshots.v1"
    hub: "telemetry.hubs.v1"
  consumer:
    enable-auto-commit: false
    attempt-timeout: 1000
grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext